Sprint 9 solution http api
zexceed111/java-kanban pull request #11
Opened 2024-09-22 21:49 UTC by zexceed111

2024-09-23 08:32 UTC, EugeneLenkevich requested changes
Привет! Спасибо за PR.

Это конечно очень муторно руками разбирать запросы и мы дальше уже этим заниматься не будем а будем использовать фреймворки :)
 В этом задании почему то хочется обратить внимание на тесты, сделать их более выразительными, отметил комментарием. Ну и сериализатор вынести бы отдельно чтобы у него была одна точка создания и он не пересоздавался каждый раз :)

2024-09-23 08:32 UTC, EugeneLenkevich commented on src/main/httphandlers/TasksHandler.java
> +                result.put(entry[0], entry[1]);
entry[0], entry[1]

Ох как потом такое разбирать будет весело, добавится еще какая то логика и станет вообще ничего не понятно :)

А в целом, этот разбор параметров можно преобразовать следующим образом, сначала вывести имя параметра и значение (оно есть или null, то есть не указано), а уже потом класть в мапу

И случаем этот метод у нас не дублируется ли, в EpiscHandler в частности, не получится ли дублирование убрать :)

2024-09-23 08:32 UTC, EugeneLenkevich commented on src/main/httphandlers/TasksHandler.java
> +        GsonBuilder gsonBuilder = new GsonBuilder();
А не получится ли такая ситуация когда у нас объект создается каждый раз на каждый запрос, это же лишние накладные расходы, этот объект (gson) можно создать один раз и переиспользовать 

Так и просится вынести создание сериализатора gson в отдельный метод и даже статическое поле какого то спец-класса и использовать везде по коду. Так мы не будем его пересоздавать в каждом классе и, плюс, у нас будет вся настройка сериализации производиться в одном месте. Иначе, поправив настройки только в одном месте, у нас разные части системы могут начать работать по разному :)

2024-09-23 08:32 UTC, EugeneLenkevich commented on test/HttpTaskServerTest.java
> +        HttpRequest request = HttpRequest.newBuilder()
Хочется всю техническую работу по созданию запросов вынести в отдельные методы, так наш код станет а) короче б) более простым для понимания, а для тестов это особо важно так как по сути своей тесты - это своеобразная документация к нашему коду и лучше когда они читаются как текстовое описание бизнес-сценариев, а дополнительный технический код это усложняет :)

2024-09-27 16:52 UTC, zexceed111 commented on src/main/httphandlers/TasksHandler.java
> +                result.put(entry[0], entry[1]);
дублирование убрать не получиться)

2024-09-29 00:47 UTC, zexceed111 commented on test/HttpTaskServerTest.java
> +        HttpRequest request = HttpRequest.newBuilder()
что то у меня не получается создать отдельные методы по созданию запросов 
Если это так будет важно, то отпишите это в комментарии, буду еще мучаться

2024-09-29 03:45 UTC, EugeneLenkevich commented on test/HttpTaskServerTest.java
> +        HttpRequest request = HttpRequest.newBuilder()
Самое простое сделать вот так, посмотри что получится, не идеально, но можно будет допить дальше :)

![image](https://github.com/user-attachments/assets/da9ab315-7001-412d-aee1-e972145d3dc9)

2024-09-29 03:47 UTC, EugeneLenkevich approved these changes
Привет, ну не, не критично, давай пойдем дальше, к тому же вряд ли мы потом будем руками http-запросы разбирать как тут, не вижу смысла это вот прямо до идеала расковыривать

2024-09-30 00:06 UTC, merged